### ISSUE TITLE
Random pixel noise - solved

### ISSUE THREAD

**Issue by larryn46** [NeoCat/ESP32-P3RGB64x32MatrixPanel#10]
I had random pixel. Making change from README.md didn'thelp:

> ## Patching GPIO to avoid eratta of ESP32

You should patch the `tools/sdk/ld/esp32.peripherals.ld` to avoid random pixel noise on the display as following:

```
/* PROVIDE ( GPIO = 0x3ff44000 ); */
PROVIDE ( GPIO = 0x60004000 );
```

 The noise persisted until I connected a ground from ESP32 ground pin to one of the Hub75 grounds. 

![32x64 no gnd](https://user-images.githubusercontent.com/6017017/52102716-e3e0e680-2596-11e9-8fa3-01de5d065ee3.jpg)

![32x64 with gnd](https://user-images.githubusercontent.com/6017017/52102728-f6f3b680-2596-11e9-910f-c4a063f1cee7.jpg)

**Comment by Stat1c-V01D** [comment]
Thats not an issue what you described here.
It is common sense to connect a common ground when working with any kind of Logic components/chips (TTL,CMOS,etc.). 
Especially the GND connection between panel and controller is very important, so that the shift register chips and the ESP have the same refference Voltage.
